name: Test Python

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run inline Python script
        shell: python
        run: |
          from datetime import datetime, UTC

          users = [
              {"name": "alice", "active": True},
              {"name": "bob", "active": False},
              {"name": "carol", "active": True},
          ]

          active_users = [u["name"].title() for u in users if u["active"]]
          now = datetime.now(UTC).isoformat()

          print(f"Active users ({len(active_users)}): {', '.join(active_users)}")
          print(f"Time: {now}")
